#!/bin/bash
# Tsunami Beta - Data Completion Script
# Generated by data_completeness_analyzer.py

set -e

DOMAIN_BACKEND_API="${DOMAIN_BACKEND_API:-http://localhost:8001}"
LOG_FILE="data_completion_$(date +%Y%m%d_%H%M%S).log"

echo "Starting data completion process..." | tee -a "$LOG_FILE"
echo "Domain Backend API: $DOMAIN_BACKEND_API" | tee -a "$LOG_FILE"
echo "Log file: $LOG_FILE" | tee -a "$LOG_FILE"
echo "" | tee -a "$LOG_FILE"

# Function to execute API call with retry
execute_with_retry() {
    local command="$1"
    local description="$2"
    local max_retries=3
    local retry=0
    
    echo "[$description] Starting..." | tee -a "$LOG_FILE"
    
    while [ $retry -lt $max_retries ]; do
        if eval "$command"; then
            echo "[$description] Completed successfully" | tee -a "$LOG_FILE"
            return 0
        else
            retry=$((retry + 1))
            echo "[$description] Failed (attempt $retry/$max_retries)" | tee -a "$LOG_FILE"
            if [ $retry -lt $max_retries ]; then
                echo "[$description] Retrying in 5 seconds..." | tee -a "$LOG_FILE"
                sleep 5
            fi
        fi
    done
    
    echo "[$description] Failed after $max_retries attempts" | tee -a "$LOG_FILE"
    return 1
}

# Check domain-backend health
echo "Checking domain-backend health..." | tee -a "$LOG_FILE"
if ! curl -f "$DOMAIN_BACKEND_API/health" > /dev/null 2>&1; then
    echo "ERROR: Domain backend is not available at $DOMAIN_BACKEND_API" | tee -a "$LOG_FILE"
    exit 1
fi
echo "Domain backend is healthy" | tee -a "$LOG_FILE"
echo "" | tee -a "$LOG_FILE"


# CRITICAL PRIORITY TASKS
echo "=== Processing CRITICAL priority tasks ===" | tee -a "$LOG_FILE"

# Task: Missing DNS analysis for subdomain api.bci.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/dns/api.bci.cl'" "Missing DNS analysis for subdomain api.bci.cl"
sleep 2


# Task: Missing DNS analysis for subdomain api.cuentafan.bancochile.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/dns/api.cuentafan.bancochile.cl'" "Missing DNS analysis for subdomain api.cuentafan.bancochile.cl"
sleep 2


# Task: Missing DNS analysis for subdomain api.github.com
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/dns/api.github.com'" "Missing DNS analysis for subdomain api.github.com"
sleep 2


# Task: Missing DNS analysis for subdomain api.security.github.com
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/dns/api.security.github.com'" "Missing DNS analysis for subdomain api.security.github.com"
sleep 2


# Task: Missing DNS analysis for subdomain beacon.www.lider.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/dns/beacon.www.lider.cl'" "Missing DNS analysis for subdomain beacon.www.lider.cl"
sleep 2


# Task: Missing DNS analysis for subdomain email.enterprise.github.com
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/dns/email.enterprise.github.com'" "Missing DNS analysis for subdomain email.enterprise.github.com"
sleep 2


# Task: Missing DNS analysis for subdomain email.finance.github.com
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/dns/email.finance.github.com'" "Missing DNS analysis for subdomain email.finance.github.com"
sleep 2


# Task: Missing DNS analysis for subdomain email.staging.finance.github.com
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/dns/email.staging.finance.github.com'" "Missing DNS analysis for subdomain email.staging.finance.github.com"
sleep 2


# Task: Missing DNS analysis for subdomain email.support.github.com
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/dns/email.support.github.com'" "Missing DNS analysis for subdomain email.support.github.com"
sleep 2


# Task: Missing DNS analysis for subdomain email.verify.github.com
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/dns/email.verify.github.com'" "Missing DNS analysis for subdomain email.verify.github.com"
sleep 2


# HIGH PRIORITY TASKS
echo "=== Processing HIGH priority tasks ===" | tee -a "$LOG_FILE"

# Task: Missing SSL/TLS certificate analysis for subdomain beacon.www.lider.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/tls/beacon.www.lider.cl'" "Missing SSL/TLS certificate analysis for subdomain beacon.www.lider.cl"
sleep 2


# Task: Missing SSL/TLS certificate analysis for subdomain puntodecompra.www.lider.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/tls/puntodecompra.www.lider.cl'" "Missing SSL/TLS certificate analysis for subdomain puntodecompra.www.lider.cl"
sleep 2


# Task: Missing SSL/TLS certificate analysis for subdomain www.about.hsbc.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/tls/www.about.hsbc.cl'" "Missing SSL/TLS certificate analysis for subdomain www.about.hsbc.cl"
sleep 2


# Task: Missing SSL/TLS certificate analysis for subdomain www.bancapropia.bancochile.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/tls/www.bancapropia.bancochile.cl'" "Missing SSL/TLS certificate analysis for subdomain www.bancapropia.bancochile.cl"
sleep 2


# Task: Missing SSL/TLS certificate analysis for subdomain www.bancochile.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/tls/www.bancochile.cl'" "Missing SSL/TLS certificate analysis for subdomain www.bancochile.cl"
sleep 2


# Task: Missing SSL/TLS certificate analysis for subdomain www.bancofalabella.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/tls/www.bancofalabella.cl'" "Missing SSL/TLS certificate analysis for subdomain www.bancofalabella.cl"
sleep 2


# Task: Missing SSL/TLS certificate analysis for subdomain www.bancoripley.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/tls/www.bancoripley.cl'" "Missing SSL/TLS certificate analysis for subdomain www.bancoripley.cl"
sleep 2


# Task: Missing SSL/TLS certificate analysis for subdomain www.bci.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/tls/www.bci.cl'" "Missing SSL/TLS certificate analysis for subdomain www.bci.cl"
sleep 2


# Task: Missing SSL/TLS certificate analysis for subdomain www.bice.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/tls/www.bice.cl'" "Missing SSL/TLS certificate analysis for subdomain www.bice.cl"
sleep 2


# Task: Missing SSL/TLS certificate analysis for subdomain www.citiconnect.bancochile.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/tls/www.citiconnect.bancochile.cl'" "Missing SSL/TLS certificate analysis for subdomain www.citiconnect.bancochile.cl"
sleep 2


# MEDIUM PRIORITY TASKS
echo "=== Processing MEDIUM priority tasks ===" | tee -a "$LOG_FILE"

# Task: Missing web technology analysis for subdomain app.cooperativa.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/tech/app.cooperativa.cl'" "Missing web technology analysis for subdomain app.cooperativa.cl"
sleep 2


# Task: Missing web technology analysis for subdomain app.santander.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/tech/app.santander.cl'" "Missing web technology analysis for subdomain app.santander.cl"
sleep 2


# Task: Missing web technology analysis for subdomain beacon.www.lider.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/tech/beacon.www.lider.cl'" "Missing web technology analysis for subdomain beacon.www.lider.cl"
sleep 2


# Task: Missing web technology analysis for subdomain login.portal.bancochile.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/tech/login.portal.bancochile.cl'" "Missing web technology analysis for subdomain login.portal.bancochile.cl"
sleep 2


# Task: Missing web technology analysis for subdomain login.portal.qa.bancochile.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/tech/login.portal.qa.bancochile.cl'" "Missing web technology analysis for subdomain login.portal.qa.bancochile.cl"
sleep 2


# Task: Missing web technology analysis for subdomain puntodecompra.www.lider.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/tech/puntodecompra.www.lider.cl'" "Missing web technology analysis for subdomain puntodecompra.www.lider.cl"
sleep 2


# Task: Missing web technology analysis for subdomain web.bancofalabella.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/tech/web.bancofalabella.cl'" "Missing web technology analysis for subdomain web.bancofalabella.cl"
sleep 2


# Task: Missing web technology analysis for subdomain web.bancoripley.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/tech/web.bancoripley.cl'" "Missing web technology analysis for subdomain web.bancoripley.cl"
sleep 2


# Task: Missing web technology analysis for subdomain web.gslbe.bancofalabella.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/tech/web.gslbe.bancofalabella.cl'" "Missing web technology analysis for subdomain web.gslbe.bancofalabella.cl"
sleep 2


# Task: Missing web technology analysis for subdomain www.about.hsbc.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/tech/www.about.hsbc.cl'" "Missing web technology analysis for subdomain www.about.hsbc.cl"
sleep 2


# Task: Missing service discovery for API/service subdomain ac-auc-cn-srv-detalle-cobros-helm.ac.prod.aws.transbank.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/services/ac-auc-cn-srv-detalle-cobros-helm.ac.prod.aws.transbank.cl'" "Missing service discovery for API/service subdomain ac-auc-cn-srv-detalle-cobros-helm.ac.prod.aws.transbank.cl"
sleep 2


# Task: Missing service discovery for API/service subdomain anupor.qa.aws.transbank.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/services/anupor.qa.aws.transbank.cl'" "Missing service discovery for API/service subdomain anupor.qa.aws.transbank.cl"
sleep 2


# Task: Missing service discovery for API/service subdomain api.bancochile.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/services/api.bancochile.cl'" "Missing service discovery for API/service subdomain api.bancochile.cl"
sleep 2


# Task: Missing service discovery for API/service subdomain api.bci.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/services/api.bci.cl'" "Missing service discovery for API/service subdomain api.bci.cl"
sleep 2


# Task: Missing service discovery for API/service subdomain api.bice.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/services/api.bice.cl'" "Missing service discovery for API/service subdomain api.bice.cl"
sleep 2


# Task: Missing service discovery for API/service subdomain api.cuentafan.bancochile.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/services/api.cuentafan.bancochile.cl'" "Missing service discovery for API/service subdomain api.cuentafan.bancochile.cl"
sleep 2


# Task: Missing service discovery for API/service subdomain api.github.com
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/services/api.github.com'" "Missing service discovery for API/service subdomain api.github.com"
sleep 2


# Task: Missing service discovery for API/service subdomain api.onepay.dev.aws.transbank.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/services/api.onepay.dev.aws.transbank.cl'" "Missing service discovery for API/service subdomain api.onepay.dev.aws.transbank.cl"
sleep 2


# Task: Missing service discovery for API/service subdomain api.onepay.prdnpci.aws.transbank.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/services/api.onepay.prdnpci.aws.transbank.cl'" "Missing service discovery for API/service subdomain api.onepay.prdnpci.aws.transbank.cl"
sleep 2


# Task: Missing service discovery for API/service subdomain api.onepay.prod.aws.transbank.cl
execute_with_retry "curl -X POST 'http://localhost:8001/api/v1/discover/services/api.onepay.prod.aws.transbank.cl'" "Missing service discovery for API/service subdomain api.onepay.prod.aws.transbank.cl"
sleep 2


# Task: Missing risk scores for 4812 services - calculate via domain analysis
execute_with_retry "echo 'Services get risk scores through domain analysis - run domain risk calculations first'" "Missing risk scores for 4812 services - calculate via domain analysis"
sleep 2


# Task: Missing provider relationships for 20 services
execute_with_retry "echo 'Provider linking is not available via API - requires manual database operations'" "Missing provider relationships for 20 services"
sleep 2


# LOW PRIORITY TASKS
echo "=== Processing LOW priority tasks ===" | tee -a "$LOG_FILE"

# Task: Missing vulnerability data for 191 technologies
execute_with_retry "echo 'Vulnerability scanning is not available via API - requires external tools'" "Missing vulnerability data for 191 technologies"
sleep 2


echo "" | tee -a "$LOG_FILE"
echo "Data completion process finished" | tee -a "$LOG_FILE"
echo "Check the log file for details: $LOG_FILE" | tee -a "$LOG_FILE"
