#!/usr/bin/env python3
"""
Create TLD Nodes Script

This script reads the TLD information JSON file generated by extract_tld_information.py
and creates TLD nodes in Neo4j with proper country and regional information. It also
associates base domains with their corresponding TLD nodes.

The script creates:
1. TLD nodes with properties like country_code, country_name, region, tld_type
2. BELONGS_TO relationships from Domain nodes to TLD nodes
3. Proper indexing for performance

Usage:
    python3 create_tld_nodes.py --input tld_information.json [--dry-run] [--update-existing]

Requirements:
    neo4j driver
"""

import argparse
import logging
import json
from neo4j import GraphDatabase
from typing import Dict, List
import time

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Neo4j connection configuration
NEO4J_URI = "bolt://localhost:7687"
NEO4J_USER = "neo4j"
NEO4J_PASSWORD = "test.password"

class TLDNodeCreator:
    def __init__(self, dry_run: bool = False):
        self.driver = GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USER, NEO4J_PASSWORD))
        self.dry_run = dry_run
        logger.info(f"Connected to Neo4j at {NEO4J_URI}")
        if dry_run:
            logger.info("🧪 DRY RUN MODE: No actual changes will be made")
    
    def close(self):
        """Close Neo4j connection"""
        if self.driver:
            self.driver.close()
            logger.info("Neo4j connection closed")
    
    def read_tld_information(self, input_file: str) -> Dict:
        """Read TLD information from JSON file"""
        try:
            with open(input_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
            logger.info(f"Read TLD information from {input_file}")
            return data
        except FileNotFoundError:
            logger.error(f"Input file {input_file} not found")
            return {}
        except Exception as e:
            logger.error(f"Error reading TLD information from {input_file}: {e}")
            return {}
    
    def create_indexes(self):
        """Create indexes for better performance"""
        indexes = [
            "CREATE INDEX IF NOT EXISTS FOR (t:TLD) ON (t.tld)",
            "CREATE INDEX IF NOT EXISTS FOR (t:TLD) ON (t.country_code)",
            "CREATE INDEX IF NOT EXISTS FOR (d:Domain) ON (d.fqdn)"
        ]
        
        if self.dry_run:
            logger.info("🧪 [DRY RUN] Would create indexes:")
            for idx in indexes:
                logger.info(f"   {idx}")
            return
        
        try:
            with self.driver.session() as session:
                for index_query in indexes:
                    session.run(index_query)
                    logger.info(f"✅ Created/verified index")
            logger.info("Indexes created successfully")
        except Exception as e:
            logger.error(f"Error creating indexes: {e}")
    
    def get_existing_tld_nodes(self) -> Dict[str, Dict]:
        """Get existing TLD nodes to avoid duplicates"""
        if self.dry_run:
            return {}
        
        query = """
        MATCH (t:TLD)
        RETURN t.tld as tld, 
               t.country_code as country_code,
               t.country_name as country_name,
               t.region as region,
               t.tld_type as tld_type,
               id(t) as node_id
        """
        
        existing_tlds = {}
        try:
            with self.driver.session() as session:
                result = session.run(query)
                for record in result:
                    tld = record['tld']
                    existing_tlds[tld] = {
                        'node_id': record['node_id'],
                        'country_code': record['country_code'],
                        'country_name': record['country_name'],
                        'region': record['region'],
                        'tld_type': record['tld_type']
                    }
                logger.info(f"Found {len(existing_tlds)} existing TLD nodes")
                return existing_tlds
        except Exception as e:
            logger.error(f"Error getting existing TLD nodes: {e}")
            return {}
    
    def create_tld_node(self, tld: str, tld_info: Dict, domain_count: int) -> bool:
        """Create a single TLD node"""
        if self.dry_run:
            logger.info(f"🧪 [DRY RUN] Would create TLD node for .{tld}:")
            logger.info(f"   Country: {tld_info.get('country_name', 'Unknown')}")
            logger.info(f"   Region: {tld_info.get('region', 'Unknown')}")
            logger.info(f"   Type: {tld_info.get('tld_type', 'unknown')}")
            logger.info(f"   Domains: {domain_count}")
            return True
        
        query = """
        MERGE (t:TLD {tld: $tld})
        SET t.country_code = $country_code,
            t.country_name = $country_name,
            t.region = $region,
            t.tld_type = $tld_type,
            t.domain_count = $domain_count,
            t.created_at = datetime(),
            t.updated_at = datetime()
        RETURN id(t) as node_id
        """
        
        params = {
            'tld': tld,
            'country_code': tld_info.get('country_code'),
            'country_name': tld_info.get('country_name', 'Unknown'),
            'region': tld_info.get('region', 'Unknown'),
            'tld_type': tld_info.get('tld_type', 'unknown'),
            'domain_count': domain_count
        }
        
        try:
            with self.driver.session() as session:
                result = session.run(query, params)
                record = result.single()
                if record:
                    logger.info(f"✅ Created/updated TLD node for .{tld} (node_id: {record['node_id']})")
                    return True
                else:
                    logger.warning(f"⚠️ No node returned for TLD .{tld}")
                    return False
        except Exception as e:
            logger.error(f"Error creating TLD node for .{tld}: {e}")
            return False
    
    def update_existing_tld_node(self, tld: str, tld_info: Dict, domain_count: int) -> bool:
        """Update an existing TLD node"""
        if self.dry_run:
            logger.info(f"🧪 [DRY RUN] Would update existing TLD node for .{tld}")
            return True
        
        query = """
        MATCH (t:TLD {tld: $tld})
        SET t.country_code = $country_code,
            t.country_name = $country_name,
            t.region = $region,
            t.tld_type = $tld_type,
            t.domain_count = $domain_count,
            t.updated_at = datetime()
        RETURN id(t) as node_id
        """
        
        params = {
            'tld': tld,
            'country_code': tld_info.get('country_code'),
            'country_name': tld_info.get('country_name', 'Unknown'),
            'region': tld_info.get('region', 'Unknown'),
            'tld_type': tld_info.get('tld_type', 'unknown'),
            'domain_count': domain_count
        }
        
        try:
            with self.driver.session() as session:
                result = session.run(query, params)
                record = result.single()
                if record:
                    logger.info(f"✅ Updated TLD node for .{tld} (node_id: {record['node_id']})")
                    return True
                else:
                    logger.warning(f"⚠️ TLD node .{tld} not found for update")
                    return False
        except Exception as e:
            logger.error(f"Error updating TLD node for .{tld}: {e}")
            return False
    
    def associate_domains_with_tld(self, domains: List[str], tld: str) -> int:
        """Create BELONGS_TO relationships between domains and TLD"""
        if self.dry_run:
            logger.info(f"🧪 [DRY RUN] Would associate {len(domains)} domains with .{tld}")
            return len(domains)
        
        if not domains:
            return 0
        
        # Process in batches to avoid memory issues
        batch_size = 1000
        total_associated = 0
        
        for i in range(0, len(domains), batch_size):
            batch = domains[i:i + batch_size]
            
            query = """
            MATCH (t:TLD {tld: $tld})
            WITH t
            UNWIND $domains as domain_fqdn
            MATCH (d:Domain {fqdn: domain_fqdn})
            MERGE (d)-[:BELONGS_TO]->(t)
            RETURN count(*) as associated_count
            """
            
            try:
                with self.driver.session() as session:
                    result = session.run(query, {'tld': tld, 'domains': batch})
                    record = result.single()
                    if record:
                        batch_count = record['associated_count']
                        total_associated += batch_count
                        logger.debug(f"Associated {batch_count} domains with .{tld} (batch {i//batch_size + 1})")
            except Exception as e:
                logger.error(f"Error associating domains with .{tld} (batch {i//batch_size + 1}): {e}")
        
        logger.info(f"✅ Associated {total_associated} domains with .{tld}")
        return total_associated
    
    def create_tld_nodes_and_associations(self, tld_data: Dict, update_existing: bool = False) -> Dict:
        """Create all TLD nodes and domain associations"""
        existing_tlds = self.get_existing_tld_nodes()
        
        results = {
            'created': 0,
            'updated': 0,
            'skipped': 0,
            'associations_created': 0,
            'errors': 0
        }
        
        logger.info(f"Processing {len(tld_data)} TLDs...")
        
        for tld, data in tld_data.items():
            tld_info = data.get('tld_info', {})
            domains = data.get('domains', [])
            domain_count = data.get('count', len(domains))
            
            logger.info(f"Processing .{tld} ({domain_count} domains)")
            
            # Check if TLD already exists
            if tld in existing_tlds:
                if update_existing:
                    if self.update_existing_tld_node(tld, tld_info, domain_count):
                        results['updated'] += 1
                    else:
                        results['errors'] += 1
                else:
                    logger.info(f"⏭️ Skipping existing TLD .{tld} (use --update-existing to update)")
                    results['skipped'] += 1
            else:
                # Create new TLD node
                if self.create_tld_node(tld, tld_info, domain_count):
                    results['created'] += 1
                else:
                    results['errors'] += 1
                    continue
            
            # Associate domains with TLD
            associations = self.associate_domains_with_tld(domains, tld)
            results['associations_created'] += associations
            
            # Small delay to avoid overwhelming Neo4j
            time.sleep(0.1)
        
        return results
    
    def print_results_summary(self, results: Dict, tld_data: Dict):
        """Print summary of results"""
        print("\n" + "="*80)
        print("TLD NODE CREATION SUMMARY")
        print("="*80)
        print(f"📊 Total TLDs processed: {len(tld_data)}")
        print(f"✅ TLD nodes created: {results['created']}")
        print(f"🔄 TLD nodes updated: {results['updated']}")
        print(f"⏭️ TLD nodes skipped: {results['skipped']}")
        print(f"❌ Errors: {results['errors']}")
        print(f"🔗 Domain associations created: {results['associations_created']}")
        
        if results['created'] + results['updated'] > 0:
            print(f"\n🎉 Successfully processed {results['created'] + results['updated']} TLD nodes")
        
        if results['errors'] > 0:
            print(f"\n⚠️ {results['errors']} TLDs had errors during processing")
        
        if results['skipped'] > 0:
            print(f"\n💡 {results['skipped']} TLDs were skipped (already exist)")
            print("   Use --update-existing to update existing TLD nodes")
    
    def verify_creation(self, tld_data: Dict):
        """Verify that TLD nodes were created correctly"""
        if self.dry_run:
            logger.info("🧪 [DRY RUN] Skipping verification")
            return
        
        query = """
        MATCH (t:TLD)
        OPTIONAL MATCH (d:Domain)-[:BELONGS_TO]->(t)
        RETURN t.tld as tld, 
               t.country_name as country_name,
               t.tld_type as tld_type,
               count(d) as associated_domains
        ORDER BY associated_domains DESC
        """
        
        try:
            with self.driver.session() as session:
                result = session.run(query)
                created_tlds = list(result)
                
                print(f"\n📊 Verification: Found {len(created_tlds)} TLD nodes in database")
                print("\n🏆 Top 10 TLDs by domain count:")
                for record in created_tlds[:10]:
                    tld = record['tld']
                    country = record['country_name']
                    tld_type = record['tld_type']
                    count = record['associated_domains']
                    print(f"   • .{tld}: {count} domains ({country}, {tld_type})")
                
                # Check for missing associations
                missing_associations = 0
                for tld, data in tld_data.items():
                    expected_count = data.get('count', 0)
                    actual_record = next((r for r in created_tlds if r['tld'] == tld), None)
                    actual_count = actual_record['associated_domains'] if actual_record else 0
                    
                    if actual_count != expected_count:
                        missing_associations += 1
                        logger.warning(f"⚠️ .{tld}: expected {expected_count}, got {actual_count} associations")
                
                if missing_associations == 0:
                    print(f"\n✅ All domain associations verified successfully")
                else:
                    print(f"\n⚠️ {missing_associations} TLDs have association mismatches")
                    
        except Exception as e:
            logger.error(f"Error during verification: {e}")

def main():
    parser = argparse.ArgumentParser(description='Create TLD nodes in Neo4j from extracted information')
    parser.add_argument('--input', '-i', required=True,
                        help='Input JSON file with TLD information')
    parser.add_argument('--dry-run', '-n', action='store_true',
                        help='Dry run mode - show what would be created without actually creating')
    parser.add_argument('--update-existing', '-u', action='store_true',
                        help='Update existing TLD nodes with new information')
    parser.add_argument('--verify', '-v', action='store_true',
                        help='Verify creation after completion')
    
    args = parser.parse_args()
    
    # Check input file exists
    from pathlib import Path
    if not Path(args.input).exists():
        print(f"❌ Input file {args.input} not found")
        print(f"💡 Generate the file first with: python3 extract_tld_information.py")
        return
    
    creator = TLDNodeCreator(dry_run=args.dry_run)
    
    try:
        # Read TLD information
        tld_information = creator.read_tld_information(args.input)
        
        if not tld_information:
            print("❌ No TLD information found in input file")
            return
        
        tld_data = tld_information.get('tld_data', {})
        if not tld_data:
            print("❌ No TLD data found in input file")
            return
        
        metadata = tld_information.get('metadata', {})
        print(f"📄 Loaded TLD information from {args.input}")
        print(f"📊 Data extracted at: {metadata.get('extraction_timestamp', 'Unknown')}")
        print(f"🌐 Total domains analyzed: {metadata.get('total_domains_analyzed', 'Unknown')}")
        print(f"🏷️  TLDs to process: {len(tld_data)}")
        
        # Confirmation for non-dry-run mode
        if not args.dry_run:
            print(f"\n🚨 This will create/update {len(tld_data)} TLD nodes and their domain associations!")
            response = input("Proceed? (y/N): ")
            if response.lower() != 'y':
                print("❌ Operation cancelled")
                return
        
        # Create indexes
        creator.create_indexes()
        
        # Create TLD nodes and associations
        print(f"\n🚀 Starting TLD node creation...")
        start_time = time.time()
        
        results = creator.create_tld_nodes_and_associations(tld_data, args.update_existing)
        
        end_time = time.time()
        
        # Print summary
        creator.print_results_summary(results, tld_data)
        
        # Verification
        if args.verify:
            creator.verify_creation(tld_data)
        
        print(f"\n⏱️ Operation completed in {end_time - start_time:.1f} seconds")
        
        if args.dry_run:
            print(f"💡 Run without --dry-run to perform actual creation")
        else:
            print(f"✅ TLD nodes and associations created successfully!")
    
    except Exception as e:
        logger.error(f"Operation failed: {e}")
    
    finally:
        creator.close()

if __name__ == "__main__":
    main()