#!/bin/bash
# setup.sh - Setup script for risk-quality module
# Part of Tsunami Beta risk-quality module

set -e

echo "🚀 Setting up Risk Quality Module..."

# Create virtual environment if it doesn't exist
if [ ! -d "venv" ]; then
    echo "📦 Creating Python virtual environment..."
    python3 -m venv venv
fi

# Activate virtual environment
echo "🔧 Activating virtual environment..."
source venv/bin/activate

# Install dependencies
echo "📚 Installing Python dependencies..."
pip install --upgrade pip
pip install -r requirements.txt

# Make scripts executable
echo "🔐 Making scripts executable..."
chmod +x *.py
chmod +x tasks/*.sh
chmod +x *.sh

# Create config file with detected credentials
echo "⚙️ Creating configuration..."
cat > config.env <<EOF
# Risk Quality Module Configuration
# Auto-generated by setup.sh

# Neo4j Configuration
NEO4J_URI=bolt://localhost:7687
NEO4J_USER=neo4j
NEO4J_PASSWORD=test.password

# Domain Backend API
DOMAIN_BACKEND_API=http://localhost:8081

# Logging
LOG_LEVEL=INFO
EOF

echo "✅ Setup completed successfully!"
echo ""
echo "📋 Quick Start:"
echo "  source venv/bin/activate"
echo "  source config.env"
echo "  python graph_validator.py --help"
echo "  python data_completeness_analyzer.py --help"
echo ""
echo "🔍 Run validation:"
echo "  python graph_validator.py --neo4j-password test.password"
echo ""
echo "📊 Run completeness analysis:"
echo "  python data_completeness_analyzer.py --neo4j-password test.password"