ollama:
  host: "http://localhost:11434"
  model: "llama3.1"
  timeout: 60
  max_tokens: 2048

neo4j:
  uri: "bolt://localhost:7687"
  user: "neo4j"
  password: "password"
  database: "neo4j"

server:
  host: "0.0.0.0"
  port: 8003
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:3001"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"